#!/usr/bin/env python3
"""
ASCON-AEAD128 FPGA UDP Test
Sends plaintext, receives nonce+AD+ciphertext+tag, verifies.
Nonce is generated by LFSR — changes per packet.
"""

import socket
import sys
import os
import time

# Add ascon-verilog repo path for SP 800-232 reference
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "fpga", "rtl", "ascon-verilog"))
from ascon import ascon_encrypt

FPGA_IP   = "192.168.1.128"
FPGA_PORT = 1234
LOCAL_IP  = "192.168.1.100"
TIMEOUT   = 5.0

# Must match RTL localparam values (little-endian byte order)
FIXED_KEY = bytes([0x0F, 0x0E, 0x0D, 0x0C, 0x0B, 0x0A, 0x09, 0x08,
                   0x07, 0x06, 0x05, 0x04, 0x03, 0x02, 0x01, 0x00])

FIXED_AD = bytes([0x00, 0xFF, 0xEE, 0xDD])

# LFSR parameters (must match RTL)
LFSR_SEED = 0xDEADBEEF_12345678_ABCDEF01_98765432
LFSR_POLY = 0x00000000_00000004_20000000_00000027
MASK_128  = (1 << 128) - 1


def lfsr_advance(nonce_int):
    """Python equivalent of RTL LFSR."""
    msb = (nonce_int >> 127) & 1
    shifted = (nonce_int << 1) & MASK_128
    if msb:
        shifted ^= LFSR_POLY
    return shifted


def nonce_int_to_bytes(nonce_int):
    """Convert 128-bit integer to 16 bytes (little-endian, matching RTL)."""
    result = []
    for i in range(16):
        result.append((nonce_int >> (i * 8)) & 0xFF)
    return bytes(result)


class NonceTracker:
    """Track LFSR nonce state."""
    def __init__(self):
        self.nonce_int = LFSR_SEED

    def get_current_bytes(self):
        return nonce_int_to_bytes(self.nonce_int)

    def advance(self):
        self.nonce_int = lfsr_advance(self.nonce_int)


# Global tracker
nonce_tracker = NonceTracker()


def send_and_receive(plaintext):
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    sock.settimeout(TIMEOUT)
    sock.bind((LOCAL_IP, 0))
    sock.sendto(plaintext, (FPGA_IP, FPGA_PORT))
    try:
        data, addr = sock.recvfrom(4096)
        return data
    except socket.timeout:
        return None
    finally:
        sock.close()


def test(plaintext, name):
    global nonce_tracker

    expected_nonce = nonce_tracker.get_current_bytes()

    print(f"\n{'='*60}")
    print(f"TEST: {name} ({len(plaintext)} bytes)")
    print(f"{'='*60}")
    print(f"  Sent:      {plaintext.hex()}")
    print(f"  Exp Nonce: {expected_nonce.hex()}")

    response = send_and_receive(plaintext)
    if response is None:
        print("  ERROR: No response (timeout)")
        return False

    print(f"  Received:  {response.hex()} ({len(response)} bytes)")

    # Parse: nonce(16) + AD(4) + CT(N) + TAG(16)
    expected_len = 16 + 4 + len(plaintext) + 16
    if len(response) != expected_len:
        print(f"  ERROR: Expected {expected_len} bytes, got {len(response)}")
        return False

    nonce = response[0:16]
    ad    = response[16:20]
    ct    = response[20:20+len(plaintext)]
    tag   = response[20+len(plaintext):20+len(plaintext)+16]

    print(f"  Nonce:     {nonce.hex()}")
    print(f"  AD:        {ad.hex()}")
    print(f"  CT:        {ct.hex()}")
    print(f"  Tag:       {tag.hex()}")

    # Verify nonce matches LFSR state
    if nonce != expected_nonce:
        print(f"  WARN: Nonce mismatch — syncing to received nonce")
        print(f"    Expected: {expected_nonce.hex()}")
        print(f"    Got:      {nonce.hex()}")
        received_int = int.from_bytes(nonce, byteorder='little')
        nonce_tracker.nonce_int = received_int

    # Verify AD
    if ad != FIXED_AD:
        print(f"  FAIL: AD mismatch! Expected {FIXED_AD.hex()}")
        nonce_tracker.advance()
        return False

    # pyascon reference using received nonce
    ref = ascon_encrypt(FIXED_KEY, nonce, FIXED_AD, plaintext, variant="Ascon-AEAD128")
    if isinstance(ref, tuple):
        ref_ct, ref_tag = bytes(ref[0]), bytes(ref[1])
    else:
        ref_ct  = ref[:len(plaintext)]
        ref_tag = ref[len(plaintext):]

    print(f"  Ref CT:    {ref_ct.hex()}")
    print(f"  Ref Tag:   {ref_tag.hex()}")

    if ct == ref_ct and tag == ref_tag:
        print(f"  >>> PASS <<<")
        nonce_tracker.advance()
        return True
    else:
        print(f"  >>> FAIL <<<")
        if ct != ref_ct:
            for i in range(len(ct)):
                if i < len(ref_ct) and ct[i] != ref_ct[i]:
                    print(f"    CT byte {i}: expected 0x{ref_ct[i]:02x}, got 0x{ct[i]:02x}")
        if tag != ref_tag:
            print(f"    Tag mismatch")
        nonce_tracker.advance()
        return False


if __name__ == "__main__":
    print("ASCON-AEAD128 FPGA UDP Encryption Test (LFSR Nonce)")
    print(f"Target: {FPGA_IP}:{FPGA_PORT}")
    print(f"Key:    {FIXED_KEY.hex()}")
    print(f"AD:     {FIXED_AD.hex()}")
    print(f"Seed:   {LFSR_SEED:032x}")

    # ARP warmup
    print("\n[ARP] Sending warmup packet...")
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    sock.sendto(b"\x00", (FPGA_IP, FPGA_PORT))
    sock.close()
    time.sleep(2)
    nonce_tracker.advance()  # warmup paketi nonce'u ilerletti
    print("[ARP] Ready.\n")

    tests = [
        (b"A",              "1-byte"),
        (b"ABCD",           "4-byte (1 word)"),
        (b"hello",          "5-byte (partial)"),
        (bytes(range(8)),   "8-byte (2 words)"),
        (b"Hello, ASCON!",  "13-byte"),
    ]

    passed = 0
    for pt, name in tests:
        if test(pt, name):
            passed += 1

    print(f"\n{'='*60}")
    print(f"Results: {passed}/{len(tests)} passed")
    print(f"{'='*60}")
