// =============================================================================
// Project:      ASCON Authenticated Encryption for UDP/IP
// Module:       ascon_udp_wrapper
// Description:  This module acts as the encryption bridge between the 
//               plaintext AXI-Stream (from PC) and the ASCON LWC core.
//
// Step-by-Step Operation:
// 1. Buffers incoming plaintext AXI-Stream into 32-bit words in a FIFO RAM.
// 2. Initializes the ASCON core (Mode 1 = Encryption) and streams the Key.
// 3. Streams the internally generated Nonce and fixed Associated Data (AD).
// 4. Streams the buffered Plaintext into ASCON; captures Ciphertext into a secondary RAM.
// 5. Extracts the 16-byte Tag generated by the ASCON core.
// 6. Transmits the final encrypted packet out via AXI-Stream in the following 
//    strict network order: [Nonce (16B) -> AD (4B) -> Ciphertext (Var) -> Tag (16B)].
// 7. Advances the Nonce for the next packet to ensure cryptographic uniqueness.
// 
// Developer:    Veysel Aras
// =============================================================================

`timescale 1ns / 1ps
`include "ascon-verilog/rtl/config.sv"

module ascon_udp_wrapper (
    input logic clk,
    input logic rst_n,

    // -------------------------------------------------------------------------
    // AXI Stream Input (FIFO - 8 bit) - Plaintext from PC (ENET0)
    // -------------------------------------------------------------------------
    input  logic [7:0] s_axis_tdata,
    input  logic       s_axis_tvalid,
    output logic       s_axis_tready,
    input  logic       s_axis_tlast,

    // -------------------------------------------------------------------------
    // AXI Stream Output (TX - 8 bit) - Encrypted data to Network (ENET1)
    // -------------------------------------------------------------------------
    output logic [7:0] m_axis_tdata,
    output logic       m_axis_tvalid,
    input  logic       m_axis_tready,
    output logic       m_axis_tlast
);

  // -------------------------------------------------------------------------
  // Internal Signals (ASCON LWC Interface)
  // -------------------------------------------------------------------------
  logic        key_valid;
  logic [31:0] key;
  logic        key_ready;

  logic [31:0] bdi;			// Block Data Input (Plaintext, Nonce, AD)
  logic [ 3:0] bdi_valid;	// Byte valid mask
  logic        bdi_ready;
  logic [ 3:0] bdi_type;	// Data type identifier
  logic        bdi_eot;		// End of Type flag
  logic        bdi_eoi;		// End of Input flag

  logic [ 3:0] mode;		// 1 = Encryption

  logic [31:0] bdo;			// Block Data Output (Ciphertext and Tag)
  logic        bdo_valid;
  logic [ 3:0] bdo_type;
  logic        bdo_eot;
  logic        bdo_eoo;
  logic        bdo_ready;

  // -------------------------------------------------------------------------
  // Ascon LWC Core Instantiation
  // -------------------------------------------------------------------------
  ascon_core u_ascon (
      .clk       (clk),
      .rst       (~rst_n),
      .key       (key),
      .key_valid (key_valid),
      .key_ready (key_ready),
      .bdi       (bdi),
      .bdi_valid (bdi_valid),
      .bdi_ready (bdi_ready),
      .bdi_type  (data_t'(bdi_type)),
      .bdi_eot   (bdi_eot),
      .bdi_eoi   (bdi_eoi),
      .mode      (mode_t'(mode)),
      .bdo       (bdo),
      .bdo_valid (bdo_valid),
      .bdo_ready (bdo_ready),
      .bdo_type  (bdo_type),
      .bdo_eot   (bdo_eot),
      .bdo_eoo   (bdo_eoo),
      .auth      (),
      .auth_valid()
  );



  // Fixed Parameters (Key and AD)
  localparam logic [127:0] FIXED_AD = 128'h000000000000000000000000DDEEFF00;
  localparam logic [127:0] FIXED_KEY = 128'h000102030405060708090A0B0C0D0E0F;

  // Dynamic Nonce Register
  logic [127:0] NONCE = 128'h0F0E0D0C0B0A09080706050403020100;

  // FSM State Definitions (Main Control Flow)
  typedef enum logic [3:0] {
    S_IDLE              = 4'd0, // Wait for plaintext AXI packet
    S_GET_UDP_FIFO_DATA = 4'd1, // Buffer plaintext into RAM
    S_SEND_MODE         = 4'd2, // Initialize ASCON (Mode = 1)
    S_SEND_KEY          = 4'd3, // Stream Key
    S_SEND_NONCE        = 4'd4, // Stream generated Nonce
    S_SEND_AD           = 4'd5, // Stream Associated Data
    S_SEND_PLAINTEXT    = 4'd6, // Stream Plaintext, capture Ciphertext
    S_GET_TAG           = 4'd7, // Capture generated MAC Tag
    S_SEND2TX           = 4'd8  // Hand over to TX Sub-FSM
  } state_t;

  // Sub-FSM for structuring the outgoing network packet
  typedef enum logic [1:0] {
    S_TX_NONCE    = 2'd0, // Send 16 bytes
    S_TX_AD       = 2'd1, // Send 4 bytes
    S_TX_ENC_DATA = 2'd2, // Send Variable bytes (Ciphertext)
    S_TX_TAG      = 2'd3  // Send 16 bytes
  } state_send_t;

  state_t              state;
  state_send_t         send_state;

  // RAM Write/Read tracking
  logic        [ 10:0] pt_fifo_wr_addr;
  logic        [ 10:0] pt_fifo_rd_addr;
  logic        [  1:0] key_word_cnt;
  logic        [  1:0] nonce_word_cnt;
  logic        [  1:0] tag_word_cnt;

  logic        [127:0] TAG; // Register to hold the generated 16-byte tag
  
  logic        [ 10:0] ct_ram_wr_addr;
  logic        [ 10:0] tx_phase_byte_cnt;
  logic        [ 10:0] pt_word_len;


  // LWC Output Capture Registers
  logic        [ 31:0] bdo_captured;
  logic                bdo_capture_valid;
  logic        [  3:0] bdi_valid_captured;

  // Data packing and alignment
  logic        [ 31:0] word_conv_buf;
  logic        [  1:0] rx_byte_idx;
  logic        [  1:0] ct_valid_bytes;
  logic        [  1:0] tx_byte_idx;

  logic                nonce_advance;	// Triggers LFSR update for Nonce
  logic                tx_trailing_word_flag;		// Flag for alignment corner cases

  // --- Plaintext FIFO RAM Signals ---
  logic                fifo_wr_en;
  logic        [  8:0] fifo_wr_addr;
  logic        [ 31:0] fifo_wr_data;
  logic        [  8:0] fifo_rd_addr;
  logic        [ 31:0] fifo_rd_data;

  // --- Ciphertext RAM Signals ---
  logic                enc_wr_en;
  logic        [  8:0] enc_wr_addr;
  logic        [ 31:0] enc_wr_data;
  logic        [  8:0] ct_ram_rd_addr;
  logic        [ 31:0] enc_rd_data;

  // --- RAM instances ---
  true_dual_port_ram_single_clock #(
      .DATA_WIDTH(32),
      .ADDR_WIDTH(9)
  ) fifo_ram (
      .clk(clk),
      .we_a(fifo_wr_en),
      .addr_a(fifo_wr_addr),
      .data_a(fifo_wr_data),
      .q_a(),
      .we_b(1'b0),
      .addr_b(fifo_rd_addr),
      .data_b(32'd0),
      .q_b(fifo_rd_data)
  );

  true_dual_port_ram_single_clock #(
      .DATA_WIDTH(32),
      .ADDR_WIDTH(9)
  ) enc_ram (
      .clk(clk),
      .we_a(enc_wr_en),
      .addr_a(enc_wr_addr),
      .data_a(enc_wr_data),
      .q_a(),
      .we_b(1'b0),
      .addr_b(ct_ram_rd_addr),
      .data_b(32'd0),
      .q_b(enc_rd_data)
  );

  // Address routing for reading Plaintext FIFO
  assign fifo_rd_addr = bdi_ready ? pt_fifo_rd_addr[8:0] : 9'd0;

  // -------------------------------------------------------------------------
  // Nonce Update Logic (LFSR)
  // This ensures a unique Nonce is generated for every single packet,
  // which is a critical requirement for ASCON security.
  // -------------------------------------------------------------------------
  always @(posedge clk) begin
    if (!rst_n) NONCE <= 128'hDEADBEEF_12345678_ABCDEF01_98765432;
    else if (nonce_advance) begin  // Pulsed once per successfully encrypted packet
      NONCE <= {NONCE[126:0], 1'b0}
						^ (NONCE[127] ? 128'h00000000_00000004_20000000_00000027 : 128'h0);
    end
  end

  // =========================================================================
  // Combinational Block — Drives ASCON inputs and AXI Outputs based on State
  // Strictly combinational to avoid latches.
  // =========================================================================
  always_comb begin
    // ----- Defaults -----
    s_axis_tready = 1'b0;
    key_valid     = 1'b0;
    key           = 32'h0;
    mode          = 4'h0;
    bdi           = 32'd0;
    bdi_valid     = 4'h0;
    bdi_type      = 4'h0;
    bdi_eot       = 1'b0;
    bdi_eoi       = 1'b0;
    bdo_ready     = 1'b0;
    m_axis_tvalid = 1'b0;
    m_axis_tlast  = 1'b0;

    case (state)
      // ---------------------------------------------------------
      S_IDLE: begin
        s_axis_tready = 1'b1; // Ready to accept new plaintext
      end

      // ---------------------------------------------------------
      S_GET_UDP_FIFO_DATA: begin
        s_axis_tready = 1'b1;
      end

      // ---------------------------------------------------------
      // Initialize ASCON Core. 
      // Mode 1 = Encryption. Must assert concurrently with key_valid.
      // ---------------------------------------------------------
      S_SEND_MODE: begin
        mode      = 4'h1;
        key_valid = 1'b1;
        key       = FIXED_KEY[(key_word_cnt*32)+:32];
      end

      // ---------------------------------------------------------
      S_SEND_KEY: begin
        key_valid = 1'b1;
        key       = FIXED_KEY[(key_word_cnt*32)+:32];
      end

      // ---------------------------------------------------------
      S_SEND_NONCE: begin
        bdi_type  = 4'h1;  // LWC Type: D_NONCE
        bdi_valid = 4'hF;
        bdi       = NONCE[(nonce_word_cnt*32)+:32];
        if (nonce_word_cnt == 2'b11) bdi_eot = 1'b1; // Last word of Nonce
      end

      // ---------------------------------------------------------
      S_SEND_AD: begin
        bdi_type  = 4'h2;  // LWC Type: D_AD
        bdi_valid = 4'hF;
        bdi       = FIXED_AD[0+:32];
        bdi_eot   = 1'b1;
        bdi_eoi   = 1'b0;
      end

      // ---------------------------------------------------------
      S_SEND_PLAINTEXT: begin
        bdo_ready = 1'b1; // Ready to catch Ciphertext
        bdi_type  = 4'h3; // LWC Type: D_MSG (Plaintext in encrypt mode)
        bdi_valid = 4'hF;
        bdi_eoi   = 1'b0;
        bdi_eot   = 1'b0;

		// Handle trailing bytes and end flags
        if (pt_fifo_wr_addr <= 1) begin
          bdi_eoi = 1'b1;
          bdi_eot = 1'b1;
          bdi     = fifo_rd_data;

		  // Calculate valid byte mask for unaligned data
          if (rx_byte_idx == 2'd0) bdi_valid = 4'b1111;  // tam word
          else bdi_valid = 4'((5'b00001 << rx_byte_idx) - 1'b1);
        end else begin
          bdi = fifo_rd_data;
        end
      end

      // ---------------------------------------------------------
      S_GET_TAG: begin
        bdo_ready = 1'b1; // Ready to catch generated MAC Tag
      end

      // ---------------------------------------------------------
      S_SEND2TX: begin
        m_axis_tvalid = 1'b1;
		// The packet officially ends when the 16th byte of the Tag is sent
        if (send_state == S_TX_TAG && tx_phase_byte_cnt == 11'd15) m_axis_tlast = 1'b1;
      end

      default: ;
    endcase
  end

  // =========================================================================
  // Sequential Block — FSM Transitions, Counters, and RAM Writes
  // =========================================================================
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      fifo_wr_en         <= 1'b0;
      fifo_wr_addr       <= 9'd0;
      fifo_wr_data       <= 32'd0;
      enc_wr_en          <= 1'b0;
      enc_wr_addr        <= 9'd0;
      enc_wr_data        <= 32'd0;
      ct_ram_rd_addr        <= 9'd0;
      rx_byte_idx  <= 2'd0;
      nonce_advance      <= 1'd0;
      state              <= S_IDLE;
      send_state         <= S_TX_NONCE;
      pt_fifo_wr_addr      <= 11'd0;
      pt_fifo_rd_addr      <= 11'd0;
      key_word_cnt       <= 2'd0;
      nonce_word_cnt     <= 2'd0;
      tag_word_cnt       <= 2'd0;
      ct_ram_wr_addr <= 11'd0;
      tx_phase_byte_cnt      <= 11'd0;
      pt_word_len             <= 11'd0;
      TAG                <= 128'd0;
      m_axis_tdata       <= 8'd0;
      bdo_captured       <= 32'd0;
      bdo_capture_valid  <= 1'b0;
      bdi_valid_captured <= 4'd0;
      tx_byte_idx <= 2'd0;
      ct_valid_bytes <= 2'd0;
      word_conv_buf        <= 32'd0;
      tx_trailing_word_flag          <= 1'd0;
    end else begin
      fifo_wr_en <= 1'b0;
      enc_wr_en  <= 1'b0;
      case (state)
        // ---------------------------------------------------------
        S_IDLE: begin
          nonce_advance <= 1'd0;
          if (s_axis_tvalid) begin
            word_conv_buf[7:0]  <= s_axis_tdata;
            rx_byte_idx <= 2'd1;
            state             <= S_GET_UDP_FIFO_DATA;

			// Handle edge case: 1-byte packet
            if (s_axis_tlast) begin
              state <= S_SEND_MODE;
              fifo_wr_en <= 1'b1;
              fifo_wr_addr <= 9'd0;
              fifo_wr_data <= {24'd0, s_axis_tdata};
              pt_fifo_wr_addr <= 11'd1;
            end
          end
        end

        // ---------------------------------------------------------
        S_GET_UDP_FIFO_DATA: begin
		  // Pack incoming 8-bit stream into 32-bit RAM words
          if (s_axis_tvalid) begin
            word_conv_buf[rx_byte_idx*8+:8] <= s_axis_tdata;
            rx_byte_idx <= rx_byte_idx + 2'd1;

            //pt_fifo_wr_addr            <= pt_fifo_wr_addr + 11'd1;

            if (rx_byte_idx == 2'd3) begin
              fifo_wr_en <= 1'b1;
              fifo_wr_addr <= pt_fifo_wr_addr[8:0];
              fifo_wr_data <= {s_axis_tdata, word_conv_buf[23:0]};
              pt_fifo_wr_addr <= pt_fifo_wr_addr + 11'd1;
            end

			// End of incoming packet
            if (s_axis_tlast) begin
			  // Write trailing unaligned bytes
              if (rx_byte_idx != 2'd3) begin
                fifo_wr_en   <= 1'b1;
                fifo_wr_addr <= pt_fifo_wr_addr[8:0];
                unique case (rx_byte_idx)
                  2'd0: fifo_wr_data <= {24'd0, s_axis_tdata};
                  2'd1: fifo_wr_data <= {16'd0, s_axis_tdata, word_conv_buf[7:0]};
                  2'd2: fifo_wr_data <= {8'd0, s_axis_tdata, word_conv_buf[15:8], word_conv_buf[7:0]};
                endcase
                pt_fifo_wr_addr <= pt_fifo_wr_addr + 11'd1;
              end
              state <= S_SEND_MODE;
            end
          end
        end

        // ---------------------------------------------------------
        S_SEND_MODE: begin
		  // Flag for handling specific alignment corner cases during TX phase
          if (pt_fifo_wr_addr != 11'd0 && pt_fifo_wr_addr != 11'd1 && rx_byte_idx == 2'd0) begin
            tx_trailing_word_flag <= 1'd1;
          end
          pt_word_len <= pt_fifo_wr_addr + 11'd1;
          state  <= S_SEND_KEY;
        end

        // ---------------------------------------------------------
        S_SEND_KEY: begin
          if (key_ready) begin
            key_word_cnt <= key_word_cnt + 2'd1;
            if (key_word_cnt == 2'b11) begin
              state        <= S_SEND_NONCE;
              key_word_cnt <= 2'b00;
            end
          end
        end

        // ---------------------------------------------------------
        S_SEND_NONCE: begin
          if (bdi_ready) begin
            nonce_word_cnt <= nonce_word_cnt + 2'd1;
            if (nonce_word_cnt == 2'b11) begin
              state          <= S_SEND_AD;
              nonce_word_cnt <= 2'd0;

            end
          end
        end

        // ---------------------------------------------------------
        S_SEND_AD: begin
          if (bdi_ready) begin
            state <= S_SEND_PLAINTEXT;
            pt_fifo_rd_addr <= pt_fifo_rd_addr + 11'd1;
          end
        end

        // ---------------------------------------------------------
        S_SEND_PLAINTEXT: begin
          // Capture Ciphertext from LWC Core
          if (bdo_valid && bdo_type == 4'h3) begin
            bdo_captured       <= bdo;
            bdo_capture_valid  <= 1'b1;
            bdi_valid_captured <= bdi_valid;
          end else begin
            bdo_capture_valid <= 1'b0;
          end

          // Cycle 2: Write captured Ciphertext into RAM
          if (bdo_capture_valid) begin
            enc_wr_en <= 1'b1;
            enc_wr_addr <= ct_ram_wr_addr[8:0];
            enc_wr_data <= bdo_captured;
            ct_ram_wr_addr <= ct_ram_wr_addr + 1;
            if (bdi_valid_captured != 4'd15) begin
              ct_valid_bytes <= bdi_valid_captured[3] + bdi_valid_captured[2]
			                        + bdi_valid_captured[1] + bdi_valid_captured[0];
            end
          end

          // Stream Plaintext to LWC Core
          if (pt_fifo_wr_addr <= 1) begin
            if (bdi_ready) begin
              state         <= S_GET_TAG;
              pt_fifo_wr_addr <= 11'd0;
              pt_fifo_rd_addr <= 11'd0;
            end
          end else begin
            if (bdi_ready) begin
              pt_word_len <= pt_word_len - 11'd1;
              pt_fifo_rd_addr <= pt_fifo_rd_addr + 11'd1;
              pt_fifo_wr_addr <= pt_fifo_wr_addr - 11'd1;
            end
          end
        end

        // ---------------------------------------------------------
        S_GET_TAG: begin
		  // Write any final Ciphertext block that arrived late
          if (bdo_capture_valid) begin
            enc_wr_en <= 1'b1;
            enc_wr_addr <= ct_ram_wr_addr[8:0];
            enc_wr_data <= bdo_captured;
            ct_ram_wr_addr <= ct_ram_wr_addr + 11'd1;
            if (bdi_valid_captured != 4'd15) begin
              ct_valid_bytes <= bdi_valid_captured[3] + bdi_valid_captured[2]
			                        + bdi_valid_captured[1] + bdi_valid_captured[0];
            end
            bdo_capture_valid <= 1'b0;
          end

		  // Capture the 4 words (16 Bytes) of the MAC Tag
          if (bdo_valid && bdo_type == 4'h4) begin
            TAG[32*tag_word_cnt+:32] <= bdo;
            tag_word_cnt             <= tag_word_cnt + 2'd1;
            if (tag_word_cnt == 2'b11) begin
              state        <= S_SEND2TX;
              send_state   <= S_TX_NONCE;
              m_axis_tdata <= NONCE[0+:8]; // Load first byte of Nonce
            end
          end
        end

        // ---------------------------------------------------------
        // TX Sub-State Machine: Constructs the Encrypted Network Packet
        // Output Order: Nonce -> AD -> Ciphertext -> MAC Tag
        // ---------------------------------------------------------
        S_SEND2TX: begin
          case (send_state)
		    // Phase 1: Stream the 16-byte Nonce
            S_TX_NONCE: begin
              if (m_axis_tready) begin
                if (tx_phase_byte_cnt == 11'd15) begin
                  tx_phase_byte_cnt <= 11'd0;
                  send_state    <= S_TX_AD;
                  m_axis_tdata  <= FIXED_AD[0 +: 8];
                end else begin
                  tx_phase_byte_cnt <= tx_phase_byte_cnt + 11'd1;
                  m_axis_tdata  <= NONCE[(tx_phase_byte_cnt+1)*8+:8];
                end
              end
            end

			// Phase 2: Stream the 4-byte Associated Data
            S_TX_AD: begin
              if (m_axis_tready) begin
                if (tx_phase_byte_cnt == 11'd3) begin
                  tx_phase_byte_cnt <= 11'd0;

				  // Check if packet was 0-byte payload (only headers)
                  if (pt_word_len == 11'd1 && rx_byte_idx == 2'd0) begin
                    // No ciphertext to send, skip directly to Tag
                    send_state   <= S_TX_TAG;
                    m_axis_tdata <= TAG[0+:8];
                  end else begin
                    // Load first word of Ciphertext from RAM
                    word_conv_buf <= enc_rd_data;
                    send_state <= S_TX_ENC_DATA;
                    m_axis_tdata <= enc_rd_data[7:0];
                    tx_byte_idx <= 2'd1;
                    ct_ram_rd_addr <= 9'd1;  // Pre-fetch next word
                    pt_fifo_rd_addr <= pt_fifo_rd_addr + 1;
                  end
                end else begin
                  tx_phase_byte_cnt <= tx_phase_byte_cnt + 11'd1;
                  m_axis_tdata  <= FIXED_AD[(tx_phase_byte_cnt+1)*8+:8];
                  if (tx_phase_byte_cnt == 11'd1) ct_ram_rd_addr <= 9'd0; // Prep RAM read
                end
              end
            end

			// Phase 3: Stream the Variable-length Ciphertext
            S_TX_ENC_DATA: begin
              if (m_axis_tready) begin
                if (pt_fifo_rd_addr == ct_ram_wr_addr) begin
                  // Handle final partial word
                  if (ct_valid_bytes != tx_byte_idx) begin
                    tx_byte_idx <= tx_byte_idx + 2'd1;
                    m_axis_tdata <= word_conv_buf[tx_byte_idx*8+:8];
                  end else begin
                    if (tx_trailing_word_flag) begin
                      tx_byte_idx <= tx_byte_idx + 2'd1;
                      m_axis_tdata <= word_conv_buf[tx_byte_idx*8+:8];
                      tx_trailing_word_flag <= 1'd0;
                    end else begin
                      tx_phase_byte_cnt <= 11'd0;
                      send_state    <= S_TX_TAG;
                      m_axis_tdata  <= TAG[0 +: 8]; // Start sending Tag
                    end

                  end
                end else begin
                  m_axis_tdata <= word_conv_buf[tx_byte_idx*8+:8];
                  tx_byte_idx <= tx_byte_idx + 2'd1;
                  tx_phase_byte_cnt <= tx_phase_byte_cnt + 11'd1;

                  // Pre-fetch next word (Cycle 2)
                  if (tx_byte_idx == 2'd2) begin
                    ct_ram_rd_addr <= pt_fifo_rd_addr[8:0] + 9'd1;
                  end

                  // Data ready from RAM, load into buffer (Cycle 3)
                  if (tx_byte_idx == 2'd3) begin
                    word_conv_buf <= enc_rd_data;  
                    pt_fifo_rd_addr <= pt_fifo_rd_addr + 1;
                  end
                end
              end
            end

			// Phase 4: Stream the 16-byte Tag
            S_TX_TAG: begin
              if (m_axis_tready) begin
                if (tx_phase_byte_cnt == 11'd15) begin
				  // Packet transmission complete. Reset system for next packet.
                  state              <= S_IDLE;
                  nonce_advance      <= 1'b1; // Trigger LFSR to cycle the Nonce
                  tx_phase_byte_cnt      <= 11'd0;
                  send_state         <= S_TX_NONCE;
                  pt_fifo_wr_addr      <= 11'd0;
                  pt_fifo_rd_addr      <= 11'd0;
                  ct_ram_wr_addr <= 11'd0;
                  tag_word_cnt       <= 2'd0;
                  tx_byte_idx <= 2'd0;
                  ct_valid_bytes <= 2'd0;
                end else begin
                  tx_phase_byte_cnt <= tx_phase_byte_cnt + 11'd1;
                  m_axis_tdata  <= TAG[(tx_phase_byte_cnt+1)*8+:8];
                end
              end
            end

            default: ;
          endcase
        end

        default: state <= S_IDLE;
      endcase
    end
  end

endmodule

